/**
 * Données de démonstration — utilisées quand le backend n'est pas disponible.
 * Toutes les pages appellent l'API normalement ; en cas d'échec, elles utilisent ces données.
 */

export const MOCK_PROPERTIES = [
  {
    id: "prop-1",
    name: "Villa Azur",
    address: "12 Promenade des Anglais, Nice",
    type: "villa",
    status: "active",
    bedrooms: 4,
    bathrooms: 3,
    max_guests: 8,
    base_price: 185,
    occupancy_rate: 87,
    monthly_revenue: 4820,
    nights_booked: 26,
    platforms: ["airbnb", "booking"],
    thumbnail: null,
  },
  {
    id: "prop-2",
    name: "Apt. Bellevue",
    address: "7 Rue d'Antibes, Cannes",
    type: "apartment",
    status: "active",
    bedrooms: 2,
    bathrooms: 1,
    max_guests: 4,
    base_price: 120,
    occupancy_rate: 82,
    monthly_revenue: 2960,
    nights_booked: 22,
    platforms: ["airbnb"],
    thumbnail: null,
  },
  {
    id: "prop-3",
    name: "Studio Monaco",
    address: "3 Avenue Princess Grace, Monaco",
    type: "studio",
    status: "active",
    bedrooms: 1,
    bathrooms: 1,
    max_guests: 2,
    base_price: 250,
    occupancy_rate: 74,
    monthly_revenue: 5500,
    nights_booked: 20,
    platforms: ["airbnb", "booking", "abritel"],
    thumbnail: null,
  },
  {
    id: "prop-4",
    name: "Mas Provençal",
    address: "Route des Colles, Mougins",
    type: "house",
    status: "active",
    bedrooms: 5,
    bathrooms: 4,
    max_guests: 10,
    base_price: 320,
    occupancy_rate: 65,
    monthly_revenue: 6200,
    nights_booked: 18,
    platforms: ["airbnb", "booking"],
    thumbnail: null,
  },
  {
    id: "prop-5",
    name: "Duplex Port Vieux",
    address: "15 Quai des Pêcheurs, Antibes",
    type: "apartment",
    status: "maintenance",
    bedrooms: 3,
    bathrooms: 2,
    max_guests: 6,
    base_price: 160,
    occupancy_rate: 0,
    monthly_revenue: 0,
    nights_booked: 0,
    platforms: ["airbnb"],
    thumbnail: null,
  },
];

export const MOCK_RESERVATIONS = [
  {
    id: "res-1",
    reservation_code: "HP-2026-001",
    guest_name: "Marie Dupont",
    guest_email: "marie.d@gmail.com",
    guest_phone: "+33 6 12 34 56 78",
    property_id: "prop-1",
    property_name: "Villa Azur",
    check_in: "2026-05-14",
    check_out: "2026-05-19",
    nights: 5,
    guests: 6,
    total_price: 925,
    source: "airbnb",
    status: "confirmed",
    created_at: "2026-04-28",
  },
  {
    id: "res-2",
    reservation_code: "HP-2026-002",
    guest_name: "Jean-Paul Martin",
    guest_email: "jp.martin@outlook.fr",
    guest_phone: "+33 6 98 76 54 32",
    property_id: "prop-2",
    property_name: "Apt. Bellevue",
    check_in: "2026-05-16",
    check_out: "2026-05-23",
    nights: 7,
    guests: 3,
    total_price: 840,
    source: "booking",
    status: "confirmed",
    created_at: "2026-04-30",
  },
  {
    id: "res-3",
    reservation_code: "HP-2026-003",
    guest_name: "Sophie & Luc Bernard",
    guest_email: "sbernard@sfr.fr",
    guest_phone: "+33 7 11 22 33 44",
    property_id: "prop-3",
    property_name: "Studio Monaco",
    check_in: "2026-05-20",
    check_out: "2026-05-25",
    nights: 5,
    guests: 2,
    total_price: 1250,
    source: "direct",
    status: "confirmed",
    created_at: "2026-05-01",
  },
  {
    id: "res-4",
    reservation_code: "HP-2026-004",
    guest_name: "Klaus Weber",
    guest_email: "k.weber@gmail.de",
    guest_phone: "+49 176 123 456",
    property_id: "prop-4",
    property_name: "Mas Provençal",
    check_in: "2026-06-01",
    check_out: "2026-06-08",
    nights: 7,
    guests: 8,
    total_price: 2240,
    source: "airbnb",
    status: "confirmed",
    created_at: "2026-05-02",
  },
  {
    id: "res-5",
    reservation_code: "HP-2026-005",
    guest_name: "Emma Rossi",
    guest_email: "emma.rossi@icloud.it",
    guest_phone: "+39 333 123 456",
    property_id: "prop-1",
    property_name: "Villa Azur",
    check_in: "2026-04-25",
    check_out: "2026-04-30",
    nights: 5,
    guests: 4,
    total_price: 925,
    source: "booking",
    status: "completed",
    created_at: "2026-04-10",
  },
  {
    id: "res-6",
    reservation_code: "HP-2026-006",
    guest_name: "Thomas Nguyen",
    guest_email: "t.nguyen@yahoo.fr",
    guest_phone: "+33 6 55 44 33 22",
    property_id: "prop-2",
    property_name: "Apt. Bellevue",
    check_in: "2026-05-10",
    check_out: "2026-05-12",
    nights: 2,
    guests: 2,
    total_price: 240,
    source: "airbnb",
    status: "cancelled",
    created_at: "2026-04-20",
  },
  {
    id: "res-7",
    reservation_code: "HP-2026-007",
    guest_name: "Carlos & Ana López",
    guest_email: "clopez@gmail.es",
    guest_phone: "+34 612 345 678",
    property_id: "prop-3",
    property_name: "Studio Monaco",
    check_in: "2026-06-10",
    check_out: "2026-06-17",
    nights: 7,
    guests: 2,
    total_price: 1750,
    source: "abritel",
    status: "confirmed",
    created_at: "2026-05-05",
  },
  {
    id: "res-8",
    reservation_code: "HP-2026-008",
    guest_name: "Isabelle Moreau",
    guest_email: "i.moreau@wanadoo.fr",
    guest_phone: "+33 6 77 88 99 00",
    property_id: "prop-4",
    property_name: "Mas Provençal",
    check_in: "2026-07-15",
    check_out: "2026-07-29",
    nights: 14,
    guests: 9,
    total_price: 4480,
    source: "direct",
    status: "confirmed",
    created_at: "2026-05-08",
  },
];

export const MOCK_TASKS = [
  {
    id: "task-1",
    title: "Ménage Villa Azur après départ Marie D.",
    type: "cleaning",
    status: "pending",
    priority: "urgent",
    property_id: "prop-1",
    property_name: "Villa Azur",
    due_date: "2026-05-19",
    assigned_to: "Fatima B.",
    notes: "Changer tous les draps. Vérifier terrasse.",
  },
  {
    id: "task-2",
    title: "Check-in Jean-Paul Martin",
    type: "checkin",
    status: "pending",
    priority: "high",
    property_id: "prop-2",
    property_name: "Apt. Bellevue",
    due_date: "2026-05-16",
    assigned_to: "Ahmed",
    notes: "Code porte : 4821. Remettre clé boîte.",
  },
  {
    id: "task-3",
    title: "Réparer volet roulant chambre 2",
    type: "maintenance",
    status: "in_progress",
    priority: "normal",
    property_id: "prop-5",
    property_name: "Duplex Port Vieux",
    due_date: "2026-05-20",
    assigned_to: "Marc T.",
    notes: "Contacter artisan. Devis reçu.",
  },
  {
    id: "task-4",
    title: "Ménage Studio Monaco",
    type: "cleaning",
    status: "done",
    priority: "normal",
    property_id: "prop-3",
    property_name: "Studio Monaco",
    due_date: "2026-05-12",
    assigned_to: "Fatima B.",
    notes: "",
  },
  {
    id: "task-5",
    title: "Check-out Emma Rossi — état des lieux",
    type: "checkout",
    status: "done",
    priority: "high",
    property_id: "prop-1",
    property_name: "Villa Azur",
    due_date: "2026-04-30",
    assigned_to: "Ahmed",
    notes: "RAS. Caution restituée.",
  },
  {
    id: "task-6",
    title: "Renouveler extincteur Mas Provençal",
    type: "maintenance",
    status: "pending",
    priority: "normal",
    property_id: "prop-4",
    property_name: "Mas Provençal",
    due_date: "2026-06-01",
    assigned_to: "Marc T.",
    notes: "Date limite légale : 01/06/2026.",
  },
  {
    id: "task-7",
    title: "Photos professionnelles Villa Azur",
    type: "other",
    status: "pending",
    priority: "low",
    property_id: "prop-1",
    property_name: "Villa Azur",
    due_date: "2026-05-30",
    assigned_to: "Ahmed",
    notes: "Photographe confirmé 30/05 à 10h.",
  },
];

export const MOCK_COMPLIANCE = [
  {
    property_id: "prop-1",
    property_name: "Villa Azur",
    registration_number: "069440B01234",
    registration_city: "Nice",
    registration_expiry: "2027-06-30",
    fiscal_regime: "lmnp",
    siret: "82341567800012",
    dpe_class: "C",
    dpe_expiry: "2028-03-15",
    nuitees_year: 87,
    nuitees_limit: 120,
    nuitees_alert_at: 96,
    current_year: 2026,
    is_compliant: true,
    alerts: [],
  },
  {
    property_id: "prop-2",
    property_name: "Apt. Bellevue",
    registration_number: "006290B05678",
    registration_city: "Paris 15e",
    registration_expiry: "2026-12-31",
    fiscal_regime: "micro_bic",
    siret: "71234567800045",
    dpe_class: "D",
    dpe_expiry: "2026-08-01",
    nuitees_year: 66,
    nuitees_limit: 120,
    nuitees_alert_at: 96,
    current_year: 2026,
    is_compliant: false,
    alerts: ["DPE expirant dans moins de 3 mois"],
  },
  {
    property_id: "prop-3",
    property_name: "Studio Monaco",
    registration_number: "",
    registration_city: "",
    registration_expiry: "",
    fiscal_regime: "lmnp",
    siret: "",
    dpe_class: "B",
    dpe_expiry: "2029-01-20",
    nuitees_year: 60,
    nuitees_limit: 120,
    nuitees_alert_at: 96,
    current_year: 2026,
    is_compliant: false,
    alerts: ["Numéro d'enregistrement manquant — requis loi Le Meur"],
  },
  {
    property_id: "prop-4",
    property_name: "Mas Provençal",
    registration_number: "013055B09012",
    registration_city: "Aix-en-Provence",
    registration_expiry: "2027-09-30",
    fiscal_regime: "lmp",
    siret: "56789012300078",
    dpe_class: "E",
    dpe_expiry: "2027-05-01",
    nuitees_year: 105,
    nuitees_limit: 120,
    nuitees_alert_at: 96,
    current_year: 2026,
    is_compliant: false,
    alerts: ["Limite de nuitées bientôt atteinte (105/120)"],
  },
];

export const MOCK_DASHBOARD_KPIS = {
  occupancy_rate: 78,
  total_revenue: 19480,
  adr: 196,
  revpar: 153,
  total_reservations: 47,
  active_properties: 4,
  period: "Mai 2026",
};

export const MOCK_REVENUE = [
  { month: "Déc", revenue: 8200 },
  { month: "Jan", revenue: 9100 },
  { month: "Fév", revenue: 10400 },
  { month: "Mar", revenue: 13200 },
  { month: "Avr", revenue: 16800 },
  { month: "Mai", revenue: 19480 },
];

export const MOCK_UPCOMING = MOCK_RESERVATIONS
  .filter((r) => r.status === "confirmed" && r.check_in >= "2026-05-11")
  .slice(0, 6);

export const MOCK_ALERTS = [
  {
    property_name: "Studio Monaco",
    message: "Numéro d'enregistrement manquant — requis loi Le Meur",
    severity: "critical",
  },
  {
    property_name: "Mas Provençal",
    message: "DPE classe E — mise à niveau recommandée avant 2028",
    severity: "warning",
  },
];

export const MOCK_CALENDAR_EVENTS = [
  { id: "ev-1", property_id: "prop-1", property_name: "Villa Azur",    start: "2026-05-14", end: "2026-05-19", guest_name: "Marie Dupont",       source: "airbnb",  type: "reservation" },
  { id: "ev-2", property_id: "prop-2", property_name: "Apt. Bellevue", start: "2026-05-16", end: "2026-05-23", guest_name: "Jean-Paul Martin",   source: "booking", type: "reservation" },
  { id: "ev-3", property_id: "prop-3", property_name: "Studio Monaco", start: "2026-05-20", end: "2026-05-25", guest_name: "Sophie & Luc Bernard", source: "direct",  type: "reservation" },
  { id: "ev-4", property_id: "prop-4", property_name: "Mas Provençal", start: "2026-06-01", end: "2026-06-08", guest_name: "Klaus Weber",         source: "airbnb",  type: "reservation" },
  { id: "ev-5", property_id: "prop-3", property_name: "Studio Monaco", start: "2026-06-10", end: "2026-06-17", guest_name: "Carlos & Ana López",  source: "abritel", type: "reservation" },
  { id: "ev-6", property_id: "prop-4", property_name: "Mas Provençal", start: "2026-07-15", end: "2026-07-29", guest_name: "Isabelle Moreau",     source: "direct",  type: "reservation" },
  { id: "ev-7", property_id: "prop-5", property_name: "Duplex Port Vieux", start: "2026-05-11", end: "2026-05-30", guest_name: "",               source: "block",   type: "block" },
  { id: "ev-8", property_id: "prop-1", property_name: "Villa Azur",    start: "2026-05-25", end: "2026-06-02", guest_name: "Pierre Laurent",      source: "booking", type: "reservation" },
];

/** Helper : enveloppe un appel API et retourne les données mock en cas d'échec */
export async function withMock<T>(
  apiCall: () => Promise<{ data: T }>,
  mockData: T
): Promise<T> {
  try {
    const res = await apiCall();
    return res.data ?? mockData;
  } catch {
    return mockData;
  }
}
